{
 "title": "SIPS V13 Dashboard",
 "time": { "from": "2026-01-30T07:02:07.459Z", "to": "2026-01-31T00:21:42.907Z" },
 "panels": [
  {
   "title": "Dynamisk Effektgräns (BTEA)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Actual Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/123/power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Calculated Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "strategy/power_limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power(L1+L2+L3)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/123/power",
     "query": "SELECT mean(\"value\") AS \"Fas 1\" FROM \"RPI_shelly/3em/123/power\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shelly/current",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Fas 1",
     "groupBy": [
      { "params": [ "value::field" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/0/current",
     "query": "SELECT mean(\"value\") AS \"Fas 1\" FROM \"RPI_shelly/3em/0/current\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Fas 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/1/current",
     "query": "SELECT mean(\"value\") AS \"Fas 2\" FROM  \"RPI_shelly/3em/1/current\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fas 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/2/current",
     "query": "SELECT mean(\"value\") AS \"Fas 1\" FROM \"RPI_shelly/3em/2/current\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ström (A)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Fas 1",
     "groupBy": [
      { "params": [ "value::field" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/1/power",
     "query": "SELECT mean(\"value\") AS \"Fas 1\" FROM \"RPI_shelly/3em/0/current\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Fas 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"Fas 2\" FROM \"RPI_shelly/3em/1/current\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fas 3",
     "query": "SELECT mean(\"value\") AS \"Fas 3\" FROM \"RPI_shelly/3em/2/current\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "radiatorer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "homey/logic/radiators",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "varmvattenberedare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "homey/logic/vvb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "avfuktare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "homey/logic/avf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Budget (Månad)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Anrop hittills",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tesla/control_counter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tesla Charge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tesla/charger_actual_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tesla/charge/current/request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tesla/charge_current_request_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energi \"Hink\" (Used vs Budget)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "alias": "Used Energy (kWh)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "strategy/energy_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Budget Target (kWh)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "strategy/energy_target",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "relä",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "Radiatorer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "homey/logic/radiators",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "VVB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "homey/logic/vvb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Avfuktare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "homey/logic/avf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Säkringtemperatur (%)",
   "type": "timeseries",
   "description": "Säkringtemperatur (%) -(Vid <70% normal drift , 70-95% soft control < 95% 95-100% trippar all last. efter tripp återkoppling pååbörjas vid T <40%)",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "value::field" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RPI_shelly/3em/1/power",
     "query": "SELECT mean(\"value\") AS \"Fas 1\" FROM \"fuse_temp_L1\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"Fas 2\" FROM \"fuse_temp_L2\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "query": "SELECT mean(\"value\") AS \"Fas 3\" FROM \"fuse_temp_L3\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Go-e Charger (Gemini)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "Actual (A)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "goe/current/actual",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Target (A)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "goe/current/request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Fasläge (1/3)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "goe/phase_mode",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}